Don't attempt to load camelCased version of the package name.
 It's unlikely that a package would have a camelCased name and an attempt to load a class with wrong case is causing NoClassDefFoundError instead of ClassNotFoundException on non case-sensitive file systems.


Former-commit-id: 4c295a28d5b31ae58a155a12b014a98289ffb3bc